#define SOKOL_IMPL
#define SOKOL_TRACE_HOOKS
#define SOKOL_GLCORE33
#include "sokol_app.h"
#include "sokol_audio.h"
#include "sokol_fetch.h"
#include "sokol_gfx.h"
#include "sokol_glue.h"
#include "sokol_log.h"
#include "sokol_time.h"
#define SOKOL_GL_IMPL
#include "util/sokol_gl.h"